# This workflow will deploy the app to Render
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      if: ${{ github.ref == 'refs/heads/main' }} # Deploy only son the main branch
      run: |
        curl -X POST \
        -H "Accept: application/json" \
        -H "Authorization: Bearer g5RRkga1FEs" \
        "https://api.render.com/deploy/srv-cu7r1h3v2p9s73bis7p0"
